# Generated by Django 5.1.6 on 2025-04-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'permissions': [('can_manage_blog', 'Может управлять блогом')], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
